apiVersion: apps/v1
kind: Deployment
metadata:
  name: e2sim
spec:
  replicas: 0
  selector:
    matchLabels:
      app: e2sim
  template:
    metadata:
      labels:
        app: e2sim
    spec:
      containers:
        - name: e2sim-container
          image: hoangtuansu/e2sim:0.7
          command:
            - sh
            - '-c'
            - sleep infinity && kpm_sim 10.180.113.156 32222
          env:
            - name: E2NODE_ID
              value: "1011"
            - name: RAN_FUNC_ID
              value: "1234"
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always

